[package]
name = "adventofcode"
version = "2020.0.0"
authors = ["Shantanu Joshi <weemadarthur@yggdrasil.in>"]

[dependencies]
regex = "1.4.2"
elapsed = "0.1.2"
chrono = "0.4.19"
itertools = "0.9.0"
lazy_static = "1.4.0"