name:                adventofcode
version:             0.1.0.0
git:                 "https://git.sr.ht/weemadarthur/adventofcode"
license:             MIT
author:              "Shantanu Joshi"
maintainer:          "weeemadarthur@yggdrasil.in"
copyright:           "Copyright: (c) 2018 Shantanu Joshi"
description:         "Advent of Code 2018: Haskell Solutions"

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - containers
    - array

executables:
  aoc:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - adventofcode
      - directory
      - timeit

tests:
  aoc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - adventofcode
      - hspec
